-- Example output of fivem-resource-builder. Secure-by-default shop, ESX/QBCore.
fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'Dei'
description 'Sample secure shop generated by fivem-resource-builder'
version '1.0.0'

shared_scripts {
    'config.lua',
}

server_scripts {
    'server/framework.lua',
    'server/main.lua',
}

client_scripts {
    'client/framework.lua',
    'client/main.lua',
}

dependencies {
    'es_extended',
}
